---
- name: 'Set hostname facts'
  set_fact:
    full_hostname: "{{ inventory_hostname }}"
    short_hostname: "{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Set hostname'
  hostname:
    name: "{{ short_hostname }}"

- name: 'Add hostname to /etc/hosts'
  lineinfile:
    dest: /etc/hosts
    line: '127.0.1.1 {{ full_hostname }} {{ short_hostname }}'
    regexp: '^127\.0\.1\.1'
    insertafter: '^127\.0\.0\.1'
    state: present
